- src/iostream.cpp
WriteConsoleW originally required the lpNumberOfCharsWritten argument.
That seems to have changed in later releases, but is required for
Windows Server 2003 and 2008. Fix a seg fault by passing the required
argument.
> Fix iostream output on older Windows

- src/iostream.cpp
Compiling with VS gives (correctly):
>  ...nowide\src\iostream.cpp(53): warning C4244: 'initializing': conversion from '__int64' to 'int', possible loss of data [...\nowide\src\nowide-static.vcxproj]
>          ...nowide\src\iostream.cpp(86): warning C4244: 'argument': conversion from '__int64' to 'DWORD', possible loss of data [...\nowide\src\nowide-static.vcxproj]
>          ...nowide\src\iostream.cpp(88): warning C4267: 'return': conversion from 'size_t' to 'int', possible loss of data [...\nowide\src\nowide-static.vcxproj]
>          ...nowide\src\iostream.cpp(161): warning C4267: 'argument': conversion from 'size_t' to 'DWORD', possible loss of data [...\nowide\src\nowide-static.vcxproj]
>          ...nowide\src\iostream.cpp(169): warning C4244: '=': conversion from '__int64' to …
> Fix conversion warnings

- include/boost/nowide/cenv.hpp
- include/boost/nowide/cstdio.hpp
- include/boost/nowide/filebuf.hpp
- include/boost/nowide/stackstring.hpp
- include/boost/nowide/system.hpp
- include/boost/nowide/windows.hpp
- src/iostream.cpp
- standalone/scoped_ptr.hpp
- standalone/utf.hpp
- test/test_codecvt.cpp
- test/test_stdio.cpp
- test/test_system.cpp
Supersedes https://github.com/boostorg/nowide/pull/40
While technically for e.g. `_wfopen` one needs `stdio.h` all compilers/stdlibs having this extension also have it when including `<cstdio>`. So use the C++ headers and the C++ functions to be consistent
> Include C++ headers instead of C variants

- include/boost/nowide/args.hpp
Using `args` will no longer silently fail
Fixes #15
> Add exceptions if winApi calls fail

- .travis.yml
The library is mostly for windows, so there isn't much to test on Linux
Reduce to oldest and most recent compilers
But still test all on pushes to eventually detect compiler version specific issues
Fixes #50
> Reduce number of Linux jobs run on PRs

- include/boost/nowide/iostream.hpp
- src/iostream.cpp
When using LTCG/LTO the unused initializer might be optimized out.
Move the operation to the ctor
> Fix potentially untied streams

- include/boost/nowide/utf8_codecvt.hpp
- test/test_codecvt.cpp
- test/test_convert.cpp
- test/test_sets.hpp
- test/test_stackstring.cpp
Converting an UTF-16 encoded string to UTF-8 with utf8_codecvt leads wrongly to a `ok` return value, but `partial` would be correct.
> Fix codecvt and improve conversion tests

- include/boost/nowide/convert.hpp
- include/boost/nowide/detail/convert.hpp
- include/boost/nowide/stackstring.hpp
The new names convey what the result will be.
Also remove helper functions to reduce number of variations.
> Move basic_convert to detail namespace and rename

- doc/main.md
- include/boost/nowide/config.hpp
- include/boost/nowide/filebuf.hpp
- include/boost/nowide/fstream.hpp
- test/test_fs.cpp
- test/test_fstream.cpp
This adds wchar_t overloads to fstream and filebuf which allows better integration with {boost,std}::filesystem::path and is mandated by C++17 on Windows.
This is then used to accept *::filesystem::path parameters for fstream classes.
> Windows: Support filesystem::path in fstream

- include/boost/nowide/filebuf.hpp
- test/benchmark_fstream.cpp
The buffer size of 4 Bytes was way to small. Now the recommended BUFSIZ is used.
Test with 5 repetitions using average speeds:
Before:
```
================== Read performance ==================
block size     stdio     std::fstream nowide::fstream
32   589.721 MB/s  661.222 MB/s  138.030 MB/s 
64   933.697 MB/s  995.025 MB/s  142.438 MB/s 
128  1235.132 MB/s 1453.555 MB/s  144.668 MB/s 
256  1472.331 MB/s 1981.950 MB/s  149.009 MB/s 
512  1543.075 MB/s 2482.728 MB/s  155.696 MB/s 
1024  1781.915 MB/s 2994.891 MB/s  158.978 MB/s 
2048  2065.877 MB/s 2918.191 MB/s  156.300 MB/s 
4096  2154.502 MB/s 2850.447 MB/s  145.350 MB/s 
8192  2895.307 MB/s 3441.936 MB/s  159.695 MB/s 
================== Write performance =================
block size     stdio     std::fstream nowide::fstream
32 …
```
> Fix degraded performance in filebuf

- include/boost/nowide/fstream.hpp
After refactoring in https://github.com/boostorg/nowide/commit/ad77653f517e1bbac2f0076d7fc49b84e4630ed3 the old filebuf instance was used instead of the inherited one leading to wrong filebuf returned by `rdbuf`
This was only found during implementing move ops as it simply initialized the underlying stream with a pointer to a non-constructed object which was (usually/always?) constructed before it was actually used and this worked so far. However this is actually not what was intended and may be UB if the stream ctor used the buffer
> Fix filebuf usage

- appveyor.yml
Currently Boost.Filesystem doesn't build with CMake super project due to pending merges to master from Boost.Optional and Boost.Fusion
--> Disable this test on master for now
> Move superproject build into own job and disable on master

- include/boost/nowide/filebuf.hpp
Without the missing include there are compiler errors with the standalone version.
> Use full ios include in filebuf.hpp

- CMakeLists.txt
- build/Jamfile.v2
- doc/changelog.dox
- include/boost/nowide/config.hpp
- include/boost/nowide/filebuf.hpp
- src/filebuf.cpp
- standalone/config.hpp
- test/check_lfs_support.cpp
The macro based solution has the downside of cluttering the global
namespace and requires duplication in both config headers.
Additionally ftello64 might not be available on some system where the
define check succeeds.
This solution uses a cpp file to wrap the functions adding enhanced
exists checks and additionally checking for overflow returning -1
(error) in that case as mandated by the standard for the filebuf
functions.
Finally a configure check determines general availability of LFS and if
it is not available the standard fseek/ftell functions are used.
> Make Large File Support more portable

- include/boost/nowide/fstream.hpp
Avoids ODR violations if some code defines BOOST_NOWIDE_USE_FILEBUF_REPLACEMENT and some does not although this is
not officially supported. This change does an effort in allowing it for
some use cases depending on the ABI used.
> Encode used filebuf in ABI

- standalone/config.hpp
Should provide a minor performance improvement to the standalone code when compiled with GCC
> Use __builtin_expect on GCC compilers also in standalone

- .appveyor.yml
- include/boost/nowide/filebuf.hpp
```
In file included from ../libs/nowide/test/test_fstream.cpp:10:
In file included from ../boost/nowide/fstream.hpp:12:
../boost/nowide/filebuf.hpp:368:20: error: result of comparison of constant 9223372036854775807 with expression of type 'const int' is always false [-Werror,-Wtautological-constant-out-of-range-compare]
if(off > std::numeric_limits<std::streamoff>::max())
~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
> Silence clang warning on armv7-a

- build/Jamfile.v2
- test/check_lfs_support.cpp
(At least) the Android NDKs stdio.h does define fseeko but not if __USE_FILE_OFFSET64
is defined and the API level is below 24.
As the usage of this macro was inconsistent between the check and the
use LFS could be wrongly detected leading to a compile failure later.
Fixes #111
> Fix LFS detection (e.g. on Android)

- test/test_fs.cpp
This seems to lead to a "boost::filesystem::status: Function not implemented" error in some environments (e.g. Docker), although it is unclear why exactly. As this is not really needed here the executable name can be used instead.
> Avoid boost::fs::unique

- CMakeLists.txt
- doc/Doxyfile
- doc/changelog.dox
- include/boost/nowide/convert.hpp
- include/boost/nowide/detail/is_string_container.hpp
- include/boost/nowide/utf/convert.hpp
- include/boost/nowide/utf/utf.hpp
- test/test_convert.cpp
- test/test_sets.hpp
- test/test_traits.cpp
This adds generic support for `string_view` by providing a trait that detects `std::string`, `std::string_view` and similar classes (such as `boost::string_view` and `nostd::string_view`.
Closes #33
> Add support for string_view

- config/check_lfs_support.cpp
- include/boost/nowide/filebuf.hpp
- src/filebuf.cpp
- test/benchmark_fstream.cpp
- test/test_fstream.cpp
- Read text files char-by-char. Reduces performance but is correct even when using seek (also indirectly via tellg), fixes #126 
- Reset stream pointers in close to avoid a use-after-free
- Fix swap for single-char states
> Fix possible invalid read operations

- include/boost/nowide/config.hpp
- standalone/config.hpp
`__MSVCRT_VERSION__` is a mingw internal and shouldn't be set by the user.
Setting it to something different than the toolchain provided value means the
headers and crt wont match which can result in crashes and build errors.
This fixes the boost build when targeting ucrt.
Downstream issue for context: https://github.com/msys2/MINGW-packages/issues/8283
> Stop defining `__MSVCRT_VERSION__`

- .appveyor.yml
- .github/workflows/posix.yml
Avoid error/Warning: "Issue detecting commit SHA. Please run actions/checkout with fetch-depth > 1 or set to 0"
This seems to lead to differing submissions between appveyor and GHA to codecov
> Increase fetch depth for coverage build

- src/filebuf.cpp
Nothing more to say. My buildroot generated toolchainfile.cmake already contains _LARGEFILE_SOURCE definition.
> fix _LARGEFILE_SOURCE redefinition on some platforms

- .github/workflows/update_standalone.yml
Use regular rm because `git diff` ignores untracked files
Also test this procedure on PRs when the HEAD commit contains "standalone"
> Fix update of standalone branch

- .github/workflows/ci.yml
- .github/workflows/ci_tests.yml
- include/boost/nowide/stat.hpp
- src/cstdio.cpp
- src/cstdlib.cpp
- src/stat.cpp
- test/test_stat.cpp
On e.g. GCC 11 used in recent MinGW-w64 and Cygwin environments undefining `__STRICT_ANSI__` is no longer supported.
However this is only required for the MinGW compilers, not the MinGW-w64 ones or on Cygwin.
Fixes #146 
- Add CI for MSYS2 using a MinGW-w64 GCC 11 compiler reproducing #146
- Add CI for more recent Cygwin to avoid regressions
- Differentiate between MinGW and MinGW-w64 as the latter does not require the `__STRICT_ANSI__` handling
- Improve `stat` function to detect differences in the struct definition between compiling and using the library
- Enable the required extension functions on Cygwin via `_GNU_SOURCE`, not by touching `__STRICT_ANSI__`
- Fix search paths for relative includes
> Improve compatibility for recent MinGW-w64 and Cygwin compilers

- .github/workflows/ci_tests.yml
- include/boost/nowide/config.hpp
- include/boost/nowide/filebuf.hpp
- include/boost/nowide/fstream.hpp
- standalone/config.hpp
- test/test_stdio.cpp
- tools/create_standalone.sh
This basically generates the standalone config.hpp from the regular config.hpp by pasting the required defines otherwise coming from `<boost/config.hpp>` into the appropriate place.
This avoids the standalone config becoming out of sync with the main one which e.g. resulted in a missing `NOWIDE_USE_WCHAR_OVERLOADS`.
This is now checked on CI by compiling (some builds) with `-Wundef` as was actually intended.
As a side effect Cygwin builds using the standalone version will use the custom filebuf implementation just as they do using the Boost version. This is due to Cygwin also using `wchar_t*` for paths which requires enabling those overloads which requires the custom filebuf.
To be exact: This is until C++17 which adds `wchar_t*` overloads to `filebuf::open` in that case, but when using …
> Fix missing standalone define

- test/test_codecvt.cpp
- test/test_system.cpp
GCC triggers a false positive:
> D:/a/_temp/msys64/mingw32/include/c++/12.1.0/bits/char_traits.h:431:56: error: 'void* __builtin_memcpy(void*, const void*, unsigned int)' accessing 2147483650 or more bytes at offsets [2, 2147483647] and 1 overlaps 2147483653 bytes at offset -3 [-Werror=restrict]
> Fix MSYS2 builds

- include/boost/nowide/filebuf.hpp
- test/test.hpp
- test/test_filebuf.cpp
- test/test_system.cpp
Only call fflush after actual output
The function is (sometimes?) described as
> For input streams (and for update streams on which the last operation was input), the behavior is undefined.
> Fix use of fflush and enhance filebuf tests

- .appveyor.yml
- build/Jamfile.v2
- test/Jamfile.v2
Recent Cygwin where the current source files path is not added to the search path automatically fail to build without manually adding the include paths to relative includes
> Fix build on recent Cygwins

- .appveyor.yml
- include/boost/nowide/filebuf.hpp
- test/test_filebuf.cpp
Implements the `xsgetn` / `xsputn` member function to do faster bulk I/O. This dramatically improves performance especially for text streams (that use unbuffered reads), see #31
Performance numbers below. Small reads on binary streams are very slightly slower due to additional checks as it still falls back to "regular" read (via `underflow`) as that is still faster due to buffering, i.e. that avoids some `fread` calls.
```
================== Read performance (binary) ==================
block size     stdio     std::fstream nowide::fstream (develop - PR)
32   876.260 MB/s  703.782 MB/s  714.873 MB/s  693.814 MB/s
64  1118.084 MB/s  928.763 MB/s  921.519 MB/s  889.736 MB/s
128  1289.297 MB/s 1149.077 MB/s 1075.776 MB/s 1065.222 MB/s
256  1384.214 MB/s 1300.754 MB/s 1222.154 MB/s 1209.963 …
```
> Improve filbuf performance

- .appveyor.yml
- include/boost/nowide/filebuf.hpp
- test/benchmark_fstream.cpp
- test/test_codecvt.cpp
- test/test_convert.cpp
- test/test_env.cpp
- test/test_filebuf.cpp
- test/test_fs.cpp
- test/test_fstream.cpp
- test/test_fstream_special.cpp
- test/test_ifstream.cpp
- test/test_iostream.cpp
- test/test_ofstream.cpp
- test/test_stackstring.cpp
- test/test_stat.cpp
- test/test_stdio.cpp
- test/test_system.cpp
- test/test_traits.cpp
- `cov-configure --msvc` is required to configure coverity for MSVC
- `PublishCoverity` seems to be so outdated that manual commands (zipping via 7z then upload via curl) work better
- Fix and add a few supressions
> Fix coverity build

- .github/workflows/release.yml
- include/boost/nowide/filebuf.hpp
- test/test_traits.cpp
Add filebuf::open overload accepting a path object to catch up with C++17 `std` classes
Add some `static_assert`s checking that the filebuf and fstream classes
can be used with `const *::filesystem::path::value_type*` and `::filesystem::path&` 
Closes #153
> Add filebuf::open overload accepting a path object and tests for const path::value_type*

- test/test_traits.cpp
Check that `_SILENCE_EXPERIMENTAL_FILESYSTEM_DEPRECATION_WARNING` is not defined already before defining it to avoid a warning (e.g. C4005 on MSVC)
Fixes #165
> Fix potential macro redefinition in test_traits

- .github/workflows/ci.yml
- doc/changelog.dox
- doc/main.dox
- include/boost/nowide/quoted.hpp
- include/boost/nowide/utf/convert.hpp
- test/test_fs.cpp
Closes #136
@SandroWissmann This will allow you to do e.g. `os << boost::nowide::quoted(path)`
I hope that meets your requirements.
> Add `boost::nowide::quoted` to read/write paths from/to streams.

- .appveyor.yml
- .github/workflows/ci_tests.yml
- .github/workflows/release.yml
- test/CMakeLists.txt
Add EXCLUDE_FROM_ALL to test binaries as per the Boost convention
Fixes #181
> CMake: Build tests only on `make test`

- .github/workflows/ci.yml
Avoid errors like
> /__e/node20/bin/node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /__e/node20/bin/node)
when using Ubuntu 16/18 containers with the @v4 actions
> GHA: Workaround node20 GLIBC issues in older Ubuntu containers

- .github/workflows/ci.yml
macos-12 will be dropped by the end of 2024 so test with the newer versions already
> GHA: Add macos-13 & 14

- include/boost/nowide/iostream.hpp
- src/iostream.cpp
- test/test_iostream.cpp
> Add test for buffering behavior of iostreams

- .github/workflows/ci_tests.yml
- doc/changelog.dox
- include/boost/nowide/cstdlib.hpp
- src/cstdlib.cpp
In order to return a non-owning pointer without memory leaks the function needs to use a static variable.
When calling it from multiple threads there is a data race during the assignment (and conversion) to this variable.
Fix by making it `thread_local`.
Fixes #189
> Make `getenv` thread-safe

- .github/workflows/ci.yml
Use containers where required to avoid picking up an incompatible libstdc++
> GHA: Avoid using gcc-toolchain change for Clang jobs and stop using Ubuntu 20 runners
